export enum SCORE_BOARD_LABEL {
  DONE = 'DONE',
  WORDS_TO_DO = 'WORDS TO DO',
  UNVERIFIED = 'UNVERIFIED',
  BASE_WORDS = 'BASE WORDS',
  QA_ISSUES = 'QA ISSUES',
  KEYS = 'KEYS',
  TEAM = 'TEAM',
}
